language: php
sudo: true


php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly

notifications:
    email: false
    irc: "irc.iiens.net#Clicky"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libtomcrypt-dev

install:
    - phpize
    - ./configure
    - make

script:
    - make test

