language: php

sudo: false

addons:
    apt:
        packages: libtomcrypt-dev

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly

matrix:
    allow_failures:
        - php: 7.0
        - php: nightly

notifications:
    email: false
    irc: "irc.iiens.net#Clicky"

before_install:
    - export TEST_PHP_EXECUTABLE=`which php`
    - export TEST_PHP_SRCDIR=`pwd`
    - export REPORT_EXIT_STATUS=1

install:
    - phpize
    - ./configure
    - make

script:
    - php -c /dev/null -d extension_dir=./modules -d extension=tomcrypt.so run-tests.php -c /dev/null -d extension_dir=./modules -d extension=tomcrypt.so -q
