language: php
sudo: true


php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - nightly

matrix:
    allow_failures:
    - php: nightly

notifications:
    email: false
    irc: "irc.iiens.net#Clicky"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libtomcrypt-dev
    - export TEST_PHP_EXECUTABLE=`which php`
    - export TEST_PHP_SRCDIR=`pwd`
    - export REPORT_EXIT_STATUS=1

install:
    - phpize
    - ./configure
    - make

script:
    - php -c /dev/null -d extension_dir=./modules -d extension=tomcrypt.so run-tests.php -c /dev/null -d extension_dir=./modules -d extension=tomcrypt.so -q
