language: php
sudo: false

addons:
  apt:
    packages:
    - libtomcrypt-dev

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly

notifications:
    email: false
    irc: "irc.iiens.net#Clicky"

install:
   - phpize
   - make

script:
    - make test

